### ISSUE TITLE
Unable to use with DatagramChannel

### ISSUE THREAD

**Issue by priere** [taktik/mpegts-streamer#3]
I’ve downloaded your Mpegts-Streamer and admire it greatly! 
I did some coding with Eclipse and tested it with VLC player, which streamed a CBR H.264 video by UDP.  
However, it seems that I’ve missed something which the code didn’t work. 
I’m sure that VLC was streaming all good because I can view the video directly bypassing the program. 
I really need your help for a stable video stream output for my project. 
Thank you very much in advance. 

Priere

Basically my code is: 

public class StreamerMain {

```
public static DatagramChannel inChannel;
public static SocketAddress inAddress;
public static DatagramSocket inSocket;

public static void main(String[] args) throws Exception {

    inChannel = DatagramChannel.open();
    inAddress = new InetSocketAddress("127.0.0.1", 1236);
    inSocket = inChannel.socket();
    inSocket.setReuseAddress(true);
    inSocket.bind(inAddress);
    inChannel.configureBlocking(true);
    inChannel.connect(inAddress);

    // When a data is received
    if (inChannel.isConnected()) {
        System.out.println("Connected");
        // Set up packet source
        MTSSource source = MTSSources.from(inChannel);
        // Set up packet sink. We will send packets directly in UDP
        MTSSink transport = UDPTransport.builder().setAddress("127.0.0.1")
                .setPort(1237).setSoTimeout(5000).setTtl(1).build();
        // Build streamer
        Streamer streamer = Streamer.builder().setSource(source)
                .setSink(transport) // We will send packets to this sink
                .build();
        // Start streaming
        streamer.stream();
    }

}
```

**Comment by antoinebaudoux** [comment]
Hello, 

I have pushed some changes, can you test again and give me the log outputs?

Thanks

**Comment by priere** [comment]
Oh, thank you so much. Let me have a try first.

**Comment by priere** [comment]
No, but I investigated the code and found out that the issue happened in NIOUtils.read(...). 
It's likely that channel.read(buffer) didn't work properly so nothing was received (i.e. buffer contained 0 data). 
I changed it to channel.receive(buffer) and commented channel.connect(...) in my code, then it started getting data (but I think this isn't a proper way to solve). 

NIOUtils: 

```
public static int read(ReadableByteChannel channel, ByteBuffer buffer) throws IOException {
    int rem = buffer.position();

    if (channel instanceof DatagramChannel) {
        SocketAddress sa;
        do {
            sa = ((DatagramChannel) channel).receive(buffer);
        } while (sa != null && buffer.hasRemaining());
        return buffer.position() - rem;
    }

    while (channel.read(buffer) != -1 && buffer.hasRemaining()) {
    }
    return buffer.position() - rem;
} 
```

**Comment by antoinebaudoux** [comment]
Indeed, you should make it work with the ByteChannel.read method.

Is the streaming working with the receive() method?

**Comment by priere** [comment]
Yes, exactly. The receive() method works well. 
I've tried to use non-blocking mode, with your code not modified (i.e. ByteChannel.read). 
The result is: NIOUtils.read() continuously run, but returns 0 (i.e. nothing in buffer). 
Again thank you so much for your help.

**Comment by priere** [comment]
I've tried many times, only the receive() method works... I couldn't find the cause. Hope that you could give me a hand. Thank you in advance.

**Comment by antoinebaudoux** [comment]
could you give me some sample code?

**Comment by priere** [comment]
Certainly. Here is the main class: 
StreamerMain.java

public class StreamerMain {

```
public static void main(String[] args) throws Exception {
    DatagramChannel inChannel = DatagramChannel
            .open(StandardProtocolFamily.INET);
    SocketAddress inAddress = new InetSocketAddress("127.0.0.1", 1236);
    DatagramSocket inSocket = inChannel.socket();
    inSocket.setReuseAddress(true);
    inSocket.bind(inAddress);
    inChannel.configureBlocking(false);
    inChannel.connect(inAddress);

    // Set up packet source
    MTSSource source = MTSSources.from(inChannel);
    // Set up packet sink. We will send packets directly in UDP
    MTSSink transport = UDPTransport.builder().setAddress("127.0.0.1")
            .setPort(1238).setSoTimeout(5000).setTtl(1).build();
    // Build streamer
    Streamer streamer = Streamer.builder().setSource(source)
            .setSink(transport) // We will send packets to this sink
            .build();
    // Start streaming
    streamer.stream();

}
```

}

In the NIOUtils class, I added some output print functions for debug. 
NIOUtils.java

public class NIOUtils {

```
public static int read(ReadableByteChannel channel, ByteBuffer buffer)
        throws IOException {
    int rem = buffer.position(), bytesRead = 0;
    System.out.println("Remaining: " + buffer.remaining());
    while (bytesRead != -1 && buffer.hasRemaining()) {
        bytesRead = channel.read(buffer);
        System.out.print("Read " + bytesRead + ", ");
        System.out.println("Remaining: " + buffer.remaining());
    }
    return buffer.position() - rem;
}

public static int skip(ByteBuffer buffer, int count) {
    int toSkip = Math.min(buffer.remaining(), count);
    buffer.position(buffer.position() + toSkip);
    return toSkip;
}
```

}

I tested the program with VLC, UDP streaming. Network tools like TCPView showed that there is data output, and the stream can be played by ffplay. However, the program was not reading packets. When I started the program, it kept on outputting the following: 

Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
Read 0, Remaining: 188000
.
.
.

**Comment by priere** [comment]
so not reading data in, and continues looping forever...
thank you very much in advance.

**Comment by antoinebaudoux** [comment]
Where is the udp stream coming from? which address and which port?

It seems you bound your channel to 127.0.0.1:1236, then you connected to the same address, which cannot be good : the connect argument is the packets source address (where the packets are coming from), not the address the channel is bound to

**Comment by priere** [comment]
I tried both, streaming from my local machine (127.0.0.1) as well as from another machine on Intranet (192.168.X.X)... Say my IP is 192.168.20.11, and that another machine is 192.168.20.13. If I set to 20.11, I'd get "Read 0, Remaining: 188000"; if I set to 20.13, then "Exception in thread "main" java.net.BindException: Cannot assign requested address: bind"

**Comment by priere** [comment]
Port 1236

**Comment by antoinebaudoux** [comment]
So you are streaming localy in unicast? what is the target host/port of your original streaming?

**Comment by antoinebaudoux** [comment]
If you are unable to make it work, you can maybe implement a new MTSSource implementation that uses the receive() method instead of the read() method

**Comment by priere** [comment]
Yes, I tried to stream from local machine and other machines in local network, unicast. Originally, I wish to do a multicast streaming, does your project support this? Thank you so much.
